Style/Tab:
  Enabled: false
Style/EmptyLineBetweenDefs:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/Documentation:
  Enabled: false
